server:
  port: 8768
  ssl: #ssl配置
    key-store: classpath:mykeystore.jks
    key-store-type: jks
    key-store-password: changeit
#    key-password: 私钥密码
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

jwt:
  public.key: classpath:app.pub






spring:
  application:
    name: oauth2-resource-server-webflux

  #oauth2 配置
  security:
    oauth2:
      resourceserver:
        jwt:
          # 公钥文件路径
          public-key-location: classpath:app.pub

          # 认证服务器提供的密钥验证路径，这种方式每次验证access_token都需要访问认证服务器
#          jwk-set-uri: http://localhost:8080/.well-known/jwks.json



