spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks
  datasource:
    url: jdbc:mysql://47.115.207.202:3306/bs
    username: root
    password: Ycs1363707959
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  data:
    mongodb:
      uri: mongodb://bs:bs@47.115.207.202:27017/bs
      database: bs
eureka:
  client:
    service-url:
      defaultZone: http://47.115.207.202:8761/eureka/
  instance:
    prefer-ip-address: true
#logging:
#  config: classpath:logs/logback-spring.xml

# 其他配置（如果需要）
server:
  port: 8082



# 日志级别配置（可选）
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.yourpackage: DEBUG
