server:
  port: 5000

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: auth-service
            uri: http://127.0.0.1:9000
            predicates:
              - Path=/auth/**
            filters:
              - StripPrefix=1

          - id: yh-service
            uri: http://127.0.0.1:8768
            predicates:
              - Path=/yh/**
            filters:
              - StripPrefix=1

#spring:
#  cloud:
#    gateway:
#      mvc:
#        routes:
#          - id: auth-service
#            uri: http://127.0.0.1:9000
#            predicates:
#              - Path=/auth/token
#            filters:
#              - RewritePath=/auth/token,/token
